# Generated by Django 3.0.6 on 2020-06-02 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200602_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='apartment_adress',
            new_name='apartment_address',
        ),
    ]
